### ISSUE TITLE
Broken on Windows WSL Ubuntu 18.04?

### ISSUE THREAD

**Issue by dasboogles** [nsmfoo/antivmdetection#63]
Followed readme to a T, getting the following error:

> --- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
> [*] Creating VirtualBox modifications ..
> Traceback (most recent call last):
>   File "antivmdetect.py", line 44, in <module>
>     for v in dmidecode.get_by_type(0):
>   File "/usr/local/lib/python3.6/dist-packages/dmidecode.py", line 122, in get_by_type
>     data = parse()
>   File "/usr/local/lib/python3.6/dist-packages/dmidecode.py", line 68, in parse
>     _data = _parse(buffer)
>   File "/usr/local/lib/python3.6/dist-packages/dmidecode.py", line 205, in _parse
>     raise ParseError("Unable to parse 'dmidecode' output")
> dmidecode.ParseError: Unable to parse 'dmidecode' output
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "antivmdetect.py", line 52, in <module>
>     dmi_info['DmiBIOSReleaseDate'] =  "string:" + v['Relase Date']
> NameError: name 'v' is not defined

I've tried troubleshooting everything, but it just isn't working and I can't find a workaround. :(

Friend of mine ran this just fine on his Windows10 WSL, but I believe his installed dependencies are much older than mine (he did this over a year ago?).

**Comment by TemeSejko** [comment]
I have this exact same issue, did you ever find a solution? @dasboogles @nsmfoo

**Comment by TemeSejko** [comment]
Issues seems to be related to WSL, https://github.com/microsoft/WSL/issues/6874.

Any idea on how to fix this or alternatives? @nsmfoo
