### ISSUE TITLE
AttributeError: 'module' object has no attribute 'bios'

### ISSUE THREAD

**Issue by jx9p3** [nsmfoo/antivmdetection#70]
Hello, I need help with this please:

--- Generate Virtualbox templates to help thwart vm det
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "antivmdetect.py", line 29, in <module>
    for v in dmidecode.bios().values():
AttributeError: 'module' object has no attribute 'bios'

I don't know what's happening, I need to fix it so I can run the code.

Milestone: 25$

**Comment by jx9p3** [comment]
Another error right now:

--- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
Traceback (most recent call last):
  File "antivmdetect.py", line 22, in <module>
    if not os.geteuid()==0:
AttributeError: 'module' object has no attribute 'geteuid'

**Comment by jx9p3** [comment]
Windows 8.1

**Comment by jx9p3** [comment]
Python 2.7
